### ISSUE TITLE
Respect embed image aspect ratio

### ISSUE THREAD

**Issue by couleurm** [Seraphli/obsidian-link-embed#38]
![image](https://github.com/Seraphli/obsidian-link-embed/assets/82747632/8618e6c0-ff0f-4ca5-b301-5139f1c8a401)

Is there some CSS trick available that could make these prettier by respecting their aspect ratio instead of defaulting to being square?

**Comment by Andrew6rant** [comment]
```CSS
.wc:has(.e > .em > a.c[href*="github"]) {
    .em {
        height: 160px;
    }
    width: 320px;
    height: 160px;
}
```
There's no way you can get the embeds to auto-respect aspect ratio using just CSS (the plugin nests `div`s strangely). So I made this CSS snippet that'll just work on GitHub embeds.

![embed_image_showcase](https://github.com/user-attachments/assets/caca366b-d586-4c2a-9f8d-104ee08e6bd7)

CC: @s1avash26 (you thumbs-up reacted the issue)
